# Generated by Django 4.1.7 on 2023-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0005_auto_20211222_2352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(max_length=1024),
        ),
    ]
